### ISSUE TITLE
Jetbrains Module Config Conflict

### ISSUE THREAD

**Issue by NyCodeGHG** [devcordde/adventofcode-20#41]
Ich verwende für meine Kotlin Lösungen IntelliJ und weil es hier eher schwierig ist ein build tool für Kotlin zu nutzen (was eigentlich auch overkill wäre), hab ich halt nur Kotlin Module für jede Lösung. Das Problem ist jetzt, dass diese ziemlich fummelig einzurichten sind und die halt im root im Ordner **.idea** liegen müssen.

Da ich nicht weiß wieviele Leute hier Jetbrains IDEs nutzen, wollte ich fragen ob es möglich wäre, den .idea Ordner aus der .gitignore rauszunehmen und dementsprechend die Config(s) zu "mergen".

@warriorzz nutzt soweit ich weiß IntelliJ und @Paul2708 PyCharm.

I use IntelliJ for my Kotlin solutions and because it is rather difficult to use a build tool for Kotlin (which would actually be overkill), I only have Kotlin modules for each solution. The problem now is that these are rather fiddly to set up and they have to be in the root in the .idea folder.

Since I don't know how many people are using Jetbrains IDEs here, I wanted to ask if it would be possible to remove the .idea folder from the .gitignore and "merge" the config (s) accordingly.

@warriorzz uses IntelliJ and @Paul2708 PyCharm as far as I know.
(Google Translate because I'm lazy.)

**Comment by JohnnyJayJay** [comment]
Ist das denn relevant? Der Ordner kann doch im gitignore stehen, aber lokal individuell benutzt und entsprechend konfiguriert werden.

**Comment by NyCodeGHG** [comment]
kommt drauf an ob man jetzt die lösungen anderer direkt ausführen können möchte.
